spring:
  application:
    name: task
  data:
    mongodb:
      database: task
      repositories:
        type: auto
      authentication-database: admin
      uri: mongodb://localhost:27017
  messages:
    basename: validation-messages